server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
spring:
  application:
    name: order-service
feign:
  hystrix:
    enabled: true
test:
  number: 1000
