server:
  port: ${PORT:9101}
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka
spring:
  application:
    name: order-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    bus:
      enable: true
      trace: 
        enable: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
    
feign:
  hystrix:
    enabled: true
test:
  number: 6666
  
  
